repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-json
    types: [file]  # override `types: [json]`
    files: \.(json)$
  - id: pretty-format-json
    args: ['--autofix', '--no-sort-keys']
    types: [file]  # override `types: [json]`
    files: \.(json)$
